#!/bin/bash
code_src=/home/cinvan/workspace/hf-code/app-trade-hfb/cmd/pinganfu/recreatetradelog.php
code_remote=jeffwang@app028:/data1/www/release/hfb/201407171456/app-trade-hfb/cmd/pinganfu/
inotifywait -mrq --timefmt '%Y%m%d-%H:%M' --format  '%T %e %w%f' -e modify,attrib,move,close_write,create,delete,delete_self  ${code_src} \
| while read file
do
	rsync -avHP --exclude=".git" --exclude=".gitignore" --exclude=".buildpath" --exclude=".project" --exclude=".settings" -e 'ssh' ${code_src} ${code_remote}
done
# rsync -avHP --exclude=".git" --exclude=".gitignore" --exclude=".buildpath" --exclude=".project" --exclude=".settings" -e 'ssh' /home/cinvan/workspace/hf-code/ www@dev1:/data1/www/dev_cloud/lixinyuan
