#!/bin/bash
static_src=/home/cinvan/workspace/hf-static/
static_remote=www@dev1:/data1/www/static_cloud/lixinyuan
inotifywait -mrq --timefmt '%Y%m%d-%H:%M' --format  '%T %e %w%f' -e modify,move,create,delete  ${static_src} \
| while read file
do
	rsync -avHP --exclude=".git" --exclude=".idea" --exclude=".gitignore" --exclude=".buildpath" --exclude=".project" --exclude=".settings" -e 'ssh' ${static_src} ${static_remote} > /dev/null 2>&1
done
# rsync -avHP --exclude=".git" --exclude=".gitignore" --exclude=".buildpath" --exclude=".project" --exclude=".settings" -e 'ssh' /home/cinvan/workspace/hf-static/ www@dev1:/data1/www/static_cloud/lixinyuan
